version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React application...
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync build/ s3://$BUCKET_NAME --delete
      - echo Invalidating CloudFront distribution...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build